app_media_image_create:
    path:     /media/image
    defaults: { _controller: AppMediaBundle:Image:create }
    methods: [POST]

app_media_image_update:
    path:     /media/image/{imageId}
    defaults: { _controller: AppMediaBundle:Image:update }
    methods: [PUT]
