shelper_media_image_create:
    path:     /media/image
    defaults: { _controller: SHelperMediaBundle:Image:create }
    methods: [POST]

shelper_media_image_update:
    path:     /media/image/{imageId}
    defaults: { _controller: SHelperMediaBundle:Image:update }
    methods: [PUT]
